### ISSUE TITLE
Faviolicons in saved bookmarks

### ISSUE THREAD

**Issue by jmacuk** [bpevs/favioli#60] opened 2022-08-09 00:36 UTC
Favioli works fine for the tab icon of my Firefox browser, but doesn't change the icon in my dropdown bookmark bar of saved bookmarks. Any way of extending the extension into all the nooks and crannies in Firefox?

**Comment by bpevs** [comment] 2022-08-09 02:20
Thanks for making an issue!  I think I am understanding this as a duplicate of https://github.com/bpevs/favioli/issues/52.  Definitely something I'm looking into.

I'll close this one since it's a duplicate, but if I am misunderstanding the issue and this is something else, then feel free to re-open!

**Closed by bpevs** 2022-08-09 02:20 UTC
Labels: 🤦‍♀️ Duplicate

**Comment by jmacuk** [comment] 2022-08-09 18:16
Yeah, that sounds about right: I was focused on the dropdown bookmarks, but
it's probably the same deal.

Thanks!
John
he/him/his 🇺🇦

If you need this document translated, please call your child’s school
principal - Si necesita este documento traducido, por favor comuníquese con
la escuela de su hijo - Se você precisa este documento traduzido, entre em
contato com a escola do seu filho - Si vous avez besoin de traduire ce
document, s'il vous plaît contacter l'école de votre enfant -
如果你需要这份文件翻译，请联系您的孩子的学校
- ،إذا كنت تحتاج /تحتاجين إلى ترجمة هذه الوثيقة إلى اللغة العربية يرجى
الاتصال بمدرسة طفلك/طفلتك - Soittakaa lapsenne koulun rehtorille, jos
tarvitsette tämän viestin käänettynä - Se Lei ha bisogno di una traduzione
di questo documento, per favore contatti il preside della scuola di Suo
scolaro - Если Вам нужно, чтобы этот документ перевели, пожалуйста
свяжитесь с директором школы Вашего ученика - jabbI'ID chugh mugh nIS, ghogh
HablI' puq DuSaQ pIn ghojmoHwI'
